### ISSUE TITLE
Warning: this looks like a license violation?

### ISSUE THREAD

**Issue by mihnita** [ydaveluy/pretty-console#2]
It looks like this code is a slightly modified version of my project, Ansi Console (https://github.com/mihnita/ansi-econsole)

Both Apache 2 and EPL 2 (which cover Ansi Console) say that you should preserve all copyright, patent, trademark, and attribution notices.

I'm afraid you are in violation.

---

It also looks like you are trying to contribute it to Eclipse, and you are preparing to publish it to Marketplace.
That is absolutely not cool.
Please, don't go ahead, or I will push back as much as I can.

**Comment by ydaveluy** [comment]
Mihai,
This is a work in progress repository, which is effectively a fork of your project.

I did a big cleaning, refactoring and renaming from ansi-econsole and lost the copyright in the process, sorry for that.

FYI I do not prepare to publish it to Marketplace for now.

This commit should solve the issue :
[https://github.com/ydaveluy/pretty-console/commit/4d5ad521a6e6d19fa705ec52c759e5ce25a2f1fd](url)
